/**
 * @module esbuild.config
 * @description MMS 插件构建脚本：dev 直出本地测试 vault，production 产出 dist/
 *
 * 输出目录优先级：环境变量 MMS_OUT_DIR > production 时 dist/ > dev 时仓库内 test-vault-local
 */
import esbuild from 'esbuild';
import process from 'node:process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_ID = 'mindmap-show';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
/** once = 单次构建到 dev 目录但不进入 watch，便于脚本里同步测试 vault */
const once = process.argv[2] === 'once';

const devOutDir = path.join(__dirname, 'test-vault-local', '.obsidian', 'plugins', PLUGIN_ID);
const outDir = process.env.MMS_OUT_DIR
  ? path.resolve(process.env.MMS_OUT_DIR)
  : prod
    ? path.join(__dirname, 'dist')
    : devOutDir;

/** 非源码资源随构建一起落到输出目录，避免手动拷贝 */
async function copyAssets() {
  await mkdir(outDir, { recursive: true });
  await copyFile(path.join(__dirname, 'manifest.json'), path.join(outDir, 'manifest.json'));
  await copyFile(path.join(__dirname, 'styles.css'), path.join(outDir, 'styles.css'));
}

const assetPlugin = {
  name: 'mms-copy-assets',
  setup(build) {
    build.onEnd(async () => {
      await copyAssets();
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: [path.join(__dirname, 'src', 'main.ts')],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtinModules,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  minify: prod,
  outfile: path.join(outDir, 'main.js'),
  plugins: [assetPlugin],
});

await context.rebuild();
console.log(`[MMS] 产物目录: ${outDir}`);

if (prod || once) {
  await context.dispose();
} else {
  await context.watch();
  console.log('[MMS] watch 模式已启动，Ctrl+C 退出');
  const files = await readdir(outDir).catch(() => []);
  console.log(`[MMS] 当前产物: ${files.join(', ') || '(空)'}`);
}
